version: 2.1

jobs:
  allure:
    docker:
      - image: oretama/allure-cli:2.13.7-alpine
    steps:
      - checkout
      - run: apk update && apk add --no-cache jq
      - run: |
          mkdir ./allure-report
          echo 'empty html' > ./allure-report/index.html
      - store_artifacts:
          path: ./allure-report
      - run: |
          curl -X GET "https://circleci.com/api/v2/project/github/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BUILD_NUM}/artifacts
          artifacts=$(curl -X GET "https://circleci.com/api/v2/project/github/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BUILD_NUM}/artifacts" \
                -H "Accept: application/json" \
                -u "$CIRCLE_API_TOKEN:" | jq '.items[0].url')
          echo $artifacts
          echo "export ARTIFACT_URL=$artifacts" >> $BASH_ENV
      - run: |
          ./bin/generate-allure-executor.sh
          mv -f executor.json ./allure-results/
          allure generate --clean
      - store_artifacts:
          path: ./allure-report

workflows:
  allure-flow:
    jobs:
      - allure:
          filters:
            branches:
              only:
                - test-circleci
