version: 2.1

jobs:
  allure:
    docker:
      - image: oretama/allure-cli:2.13.7-alpine
    steps:
      - checkout
      - run: |
          mkdir ./allure-report
          echo 'empty html' > ./allure-report/index.html
      - store_artifacts:
          path: ./allure-report
      - run: |
          echo "export ARTIFACT_URL=https://circleci.com/api/v1.1/project/github/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BUILD_NUM}/artifacts/0/~/repo/output/reporter.html?circle-token=${ARTIFACT_TOKEN}" >> $BASH_ENV
          source $BASH_ENV
          echo $ARTIFACT_URL
      - run: |
          ./bin/generate-allure-executor.sh
          mv -f executor.json ./allure-results/
          allure generate
      - store_artifacts:
          path: ./allure-report

workflows:
  allure-flow:
    jobs:
      - allure:
          filters:
            branches:
              only:
                - test-circleci
